subscription newActivity($assetId: ID!, $organisationId: ID!, $from: Date!) {\n newActivity(assetId: $assetId, organisationId: $organisationId, from: $from) {\n ...activityData\n __typename\n }\n}\n\nfragment activityData on Activity {\n id\n time\n locations {\n id\n name\n __typename\n }\n geocoding {\n fullAddress\n address {\n number\n road\n suburb\n city\n district\n __typename\n }\n __typename\n }\n speedLimit {\n limit\n type\n available\n __typename\n }\n telemetry {\n gps {\n coords\n speed\n heading\n quality {\n hdop\n satellites\n __typename\n }\n __typename\n }\n gsm {\n signal\n __typename\n }\n mainVoltage\n backupVoltage\n alert {\n type\n __typename\n }\n __typename\n }\n primaryInputActive\n __typename\n}\n